apiVersion: apiextensions.k8s.io/v1alpha1
kind: CustomResourceDefinition
metadata:
    name: applicationtemplates.microsoft.com
    namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
    group: microsoft.com
    names:
        kind: ApplicationTemplate
        plural: applicationtemplates
        singular: applicationtemplate
        shortNames:
            - wa
    scope: Namespaced
    versions:
        - name: v1alpha1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              ref:
                                  type: string
                              repo:
                                  type: string
                              path:
                                  type: string
                          required: ["repo", "path"]
