apiVersion: v1
kind: Service
metadata:
    name: application-api
    namespace: {{ .Release.Namespace }}
    labels:
        app: application-api
    annotations:
        prometheus.io/scrape: "true"
spec:
    selector:
        app: application-api
    ports:
        - name: http
          port: 80
