apiVersion: example.com/v1
kind: Workload
metadata:
    name: cluster-agent-main
    namespace: default
spec:
    #    assignment:
    #        - id: all # match all clusters
    #          matching:
    #              - label: cloud
    #                value: azure
    reconciler: gitops # mechanism used to reconciling workloads (currently only gitops supported)
    templates:
        workload: # this template will be deployed per workload cluster assigned.
            method: git
            source: "git@github.com:timfpark/cluster-agent" # reconciler specific identifier for a source
            path: "templates/deployment" # reconciler specific path within that source

    #   global: # this template will be deployed once for the whole workload on control plane
    #       source: "https://github.com/timfpark/test-workload/global"
    #       path: "templates/deployment" # reconciler specific path within that source

    values: # values used during templating
        imageTag: 20210701T165254Z # {"$imagepolicy": "flux-system:cluster-agent-main:tag"}
        ring: main
