apiVersion: example.com/v1
kind: Workload
metadata:
    name: cluster-agent-workload
    namespace: default
spec:
    #    assignment:
    #        - id: all # match all clusters
    #          matching:
    #              - label: cloud
    #                value: azure
    reconciler: gitops # specifies the mechanism used to reconcile workloads (currently only gitops supported)
    templates:
        cluster: # this template will be deployed per workload cluster assigned.
            source: "git@github.com:timfpark/cluster-agent" # reconciler specific identifier for a source
            path: "deployment" # reconciler specific path within that source
#        global: # this template will be deployed once for the whole workload on control plane
#            source: "https://github.com/timfpark/test-workload/global"
#    overrides:
#        azure: # name of override
#            matching:
#                - label: cloud
#                  value: azure
#            overrides:
#                - key: endpoint
#                  value: db.azure.com
#        eastus:
#            label: region
#            matching: eastus
