apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: applications.example.com
    namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
    group: example.com
    names:
        kind: Application
        plural: applications
        singular: application
        shortNames:
            - a
    scope: Namespaced
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              reconciler:
                                  type: string
                              templates: # templates define the resources that are deployed
                                  type: object
                                  properties:
                                      application: # application template deployed for each cluster
                                          type: object
                                          properties:
                                              method:
                                                  type: string # defaults to git
                                              source:
                                                  type: string
                                              path:
                                                  type: string
                                          required: ["source", "path"]
                                  required: ["application"]
                              values:
                                  x-kubernetes-preserve-unknown-fields: true
                                  type: object
                          required: ["templates"]
