apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: workloads.example.com
    namespace: default # For easier deployment and avoid permissions collisions on most clusters, the resource is namespace-scoped. More information at: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/
spec:
    group: example.com
    names:
        kind: Workload
        plural: workloads
        singular: workload
        shortNames:
            - workload
    scope: Namespaced
    versions:
        - name: v1
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  properties:
                      spec:
                          type: object
                          properties:
                              templates: # templates define the resources that are deployed
                                  type: object
                                  properties:
                                      deployment: # deployment templates are deployed for each cluster
                                          type: object
                                          properties:
                                              source:
                                                  type: string
                                              location:
                                                  type: string
                                          required: ["source", "location"]
                                  required: ["deployment"]
