use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `ApplicationAssignment` resource, directly
/// reflects context of the `applicationassignments.example.com.yaml` file to be found in this repository.
/// The `ApplicationAssigment` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "example.com",
    version = "v1",
    kind = "ApplicationAssignment",
    plural = "applicationassignments",
    derive = "PartialEq",
    namespaced
)]
pub struct ApplicationAssignmentSpec {
    pub application: String,
    pub cluster: String,
}
