use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Struct corresponding to the Specification (`spec`) part of the `ApplicationAssignment` resource, directly
/// reflects context of the `applicationassignments.microsoft.com.yaml` file to be found in this repository.
/// The `ApplicationAssigment` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "microsoft.com",
    version = "v1alpha1",
    kind = "ApplicationAssignment",
    plural = "applicationassignments",
    derive = "PartialEq",
    namespaced
)]
pub struct ApplicationAssignmentSpec {
    pub environment: String,
    pub cluster: String,

    pub values: Option<HashMap<String, String>>,
}
