use std::collections::HashMap;

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `Cluster` resource, directly
/// reflects context of the `clusters.microsoft.com.yaml` file to be found in this repository.
/// The `Cluster` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "microsoft.com",
    version = "v1alpha1",
    kind = "Cluster",
    plural = "clusters",
    derive = "PartialEq",
    namespaced
)]
pub struct ClusterSpec {
    pub name: String,
    pub labels: HashMap<String, String>,
    pub environments: Vec<String>,
}
