use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Struct corresponding to the Specification (`spec`) part of the `WorkloadAssignment` resource, directly
/// reflects context of the `workloadassignments.example.com.yaml` file to be found in this repository.
/// The `WorkloadAssigment` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "example.com",
    version = "v1",
    kind = "WorkloadAssignment",
    plural = "workloadassignments",
    derive = "PartialEq",
    namespaced
)]
pub struct WorkloadAssignmentSpec {
    pub workload: String,
    pub cluster: String
}
