use std::collections::HashMap;

use kube::CustomResource;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use super::templates_spec::TemplatesSpec;

/// Struct corresponding to the Specification (`spec`) part of the `Workload` resource, directly
/// reflects context of the `workloads.example.com.yaml` file to be found in this repository.
/// The `Workload` struct will be generated by the `CustomResource` derive macro.
#[derive(CustomResource, Serialize, Deserialize, Debug, PartialEq, Clone, JsonSchema)]
#[kube(
    group = "example.com",
    version = "v1",
    kind = "Workload",
    plural = "workloads",
    derive = "PartialEq",
    namespaced
)]
pub struct WorkloadSpec {
    pub templates: TemplatesSpec,
    pub values: Option<HashMap<String, String>>
}
