# required settings

image:
    repository: tpark.azurecr.io
    tag: 20211006T162343Z

port: 80

resources:
    requests:
        cpu: "250m"
        memory: "256Mi"
    limits:
        cpu: "250m"
        memory: "512Mi"
